name: workflow-1
on:
  workflow_dispatch: 
      
jobs:

  first-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: printing welcome message job1
        run: |
          sleep 10
          echo "welcome to github actions by job1"
          
      - name: printing bye message job1
        run: |
          echo "bye from job1"
          
      - name: printing 1 more bye message job1
        run: |
          echo "one more bye from job1"
