name: demo wf for builidng the app with custom actions
on: workflow_dispatch

jobs:
  packing-the-app:
    name: job for packing-the-app
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        
      - name: set up java 21
        uses: actions/setup-java@21
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          
      - name: build the app
        run: |
          mvn clean package
          ls -a
      
