name: env var demo
on: workflow_dispatch

env:
  APP_NAME: my-demo-app

jobs:

  first-job:
    env:
      APP_NAME: my-demo-app-job
    runs-on: ubuntu-latest
    steps:
      - name: step1 steps
        env:
          APP_NAME: my-demo-app-step
        run: |
          echo "======================"
          echo "APP_NAME is $APP_NAME"
          echo "======================"               
