## checkout
## java 21
## run tests
## upload artifacts

## build - checkout
## setup java 21
## package
## upload artifacts

name: this is demo of ci
on: workflow_dispatch

jobs:

  build-package-job:
    name: build and package job
    runs-on: ubuntu-24.04
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
  
      - name: setup java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
          
      - name: package app
        run: mvn package -DskipTests
  
      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifact
          path: target/*.jar
          retention-days: 2
        
  download-package-job:
    name: download package job
    runs-on: ubuntu-24.04
    needs: build-package-job
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-artifact
          path: ./download-folder
          retention-days: 2
      - name: verify the downloaded artifact
        run: |
         run: ls -la ./download-folder/
    
